services:
  koordtool:
    image: ghcr.io/ait-cs-iaas/koord2ool:latest
    environment:
      - LIMESURVEY_RPC_API=https://lime.cyberrange.rocks/index.php/admin/remotecontrol
    ports:
      - "8080:80"
